blank_issues_enabled: false
contact_links:
  - name: Luminous Music Player Discussion
    url: https://github.com/esoltys/luminous/discussions
    about: Ask questions, share ideas, or discuss features